/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package operation;

import org.junit.Test;
import static org.junit.Assert.*;

public class SubtractionTest {
    @Test public void testSubtraction() {
       Subtraction subtraction = new Subtraction();
       assertEquals(5, subtraction.subtract(14, 9));
    }
}
